spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db-mcms-open?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: lishuai4899
    filters: wall,mergeStat
    type: com.alibaba.druid.pool.DruidDataSource
